# Generated by Django 4.2.4 on 2023-08-31 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminVivero', '0002_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('codigo_vivero', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Número de identificación del vivero')),
                ('cultivo_vivero', models.CharField(max_length=100, verbose_name='Cultivo del vivero')),
                ('numero_catastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminVivero.finca')),
            ],
        ),
    ]
