# Generated by Django 4.2.4 on 2023-09-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminVivero', '0003_vivero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('registro_ICA', models.IntegerField(primary_key=True, serialize=False, verbose_name='Registro ICA colombia')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('aplicacion_producto', models.IntegerField(verbose_name='Frecuencia de aplicación')),
                ('valor_producto', models.FloatField(verbose_name='Precio del producto en COP')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_labor', models.DateField(verbose_name='Fecha de inicio de la labor')),
                ('tipo_labor', models.CharField(choices=[('Control Plagas', 'Control de Plagas'), ('Control Hongos', 'Control de Hongos'), ('Control Fertilizante', 'Control de Fertilizantes')], max_length=100)),
                ('descripcion_labor', models.CharField(max_length=500, verbose_name='Descripción de la labor')),
                ('nombre_hongo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del hongo')),
                ('periodo_carencia', models.IntegerField(blank=True, null=True, verbose_name='Periodo de carencia')),
                ('fecha_aplicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de aplicación fertilizante')),
                ('codigo_vivero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminVivero.vivero')),
                ('registro_ICA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminVivero.producto')),
            ],
        ),
    ]
